### ISSUE TITLE
glibc-for-termux support 32bit arm and bug fixes

### ISSUE THREAD

**Issue by ExtinctDrift19** [Maxython/glibc-for-termux#3]
glibc 32

**Comment by Maxython** [comment]
glibc-for-termux will support all architectures, it's just a matter of time. So I understand what you mean by 32bit - `arm` architecture (`armv7`)?  If yes, support for this architecture will not appear soon, since I do not have a device with `arm`.

**Comment by ExtinctDrift19** [comment]
Yes

**Comment by Randomxdp** [comment]
> glibc-for-termux will support all architectures, it's just a matter of time. So I understand what you mean by 32bit - `arm` architecture (`armv7`)? If yes, support for this architecture will not appear soon, since I do not have a device with `arm`.

can i help you with compiling for arm since i have a armv8l (but armv7 compatible) device? with termux

**Comment by ExtinctDrift19** [comment]
Yes can i help you with compiling for arm since i have a armv8l (but armv7 compatible) device with termux?

**Comment by Randomxdp** [comment]
> Yes can i help you with compiling for arm since i have a armv8l (but armv7 compatible) device with termux?

bruh its my device

**Comment by ExtinctDrift19** [comment]
my device samsung a10 galaxy

**Comment by Randomxdp** [comment]
after running gcc i got this bad sys call
![Screenshot_20221005_222700](https://user-images.githubusercontent.com/95031664/194193998-d3730613-777d-407a-86d8-fa1f1e07aeaa.jpg)
and heres a bit of gdb in case you need it
![Screenshot_20221005_222831_com termux](https://user-images.githubusercontent.com/95031664/194194004-c4385b9a-b672-4b1b-89a3-35dcab04062c.jpg)

**Comment by Randomxdp** [comment]
after running strace i got this, weird
![Screenshot_20221005_224022](https://user-images.githubusercontent.com/95031664/194195372-1dccd028-3c5c-4401-9055-203b3019bc32.jpg)

**Comment by Maxython** [comment]
Thanks for reporting the bug.  I'll fix it soon and update the package archive in the release.

Is it just gcc or all glibc commands not working?

**Comment by Randomxdp** [comment]
![Screenshot_20221006_081441](https://user-images.githubusercontent.com/95031664/194299171-e90bba76-c3ff-49dc-8412-9b88a824df92.jpg)
yep

**Comment by Maxython** [comment]
@Randomxdp, I need you to do the following:

- Install the https://github.com/torvalds/linux/blob/master/samples/vfs/test-statx.c file
- Compile it via clang (bionic)
- Run it (`./a.out test-statx.c`) and send me the result of running it.

I need this so that I understand whether you have a `statx` system call (according to the bionic system call standard, it must exist - https://android.googlesource.com/platform/bionic/+/master/libc/SYSCALLS.TXT#214).

**Comment by Randomxdp** [comment]
my luck.
![Screenshot_20221006_195933_com termux](https://user-images.githubusercontent.com/95031664/194433670-9063e655-75f6-4455-bfa2-8ec77dd17461.jpg)

**Comment by Maxython** [comment]
Now, I would like to get the result of the `termux-info` command. And also try running some glibc commands with proot (for example: `proot gcc`).

**Comment by Randomxdp** [comment]
termux-info
![Screenshot_20221007_080549](https://user-images.githubusercontent.com/95031664/194539458-4c04f374-1031-4291-a853-31dad89a434c.jpg)
and proot fixes it?
![Screenshot_20221007_080618](https://user-images.githubusercontent.com/95031664/194539475-1085c17c-b54f-4d62-9a7c-79721c1822e2.jpg)

**Comment by Maxython** [comment]
Similar case: https://github.com/libuv/libuv/issues/2282 (I left it for further action)

**Comment by Maxython** [comment]
@Randomxdp, install this glibc and try to compile something based on gcc-glibc.

```
wget https://github.com/Maxython/glibc-for-termux/files/9738900/glibc-2.36-1-armv7.zip
unzip glibc-2.36-1-armv7.zip
proot --link2symlink pacman -U glibc-2.36-1-any.pkg.tar.xz
```

[glibc-2.36-1-armv7.zip](https://github.com/Maxython/glibc-for-termux/files/9738900/glibc-2.36-1-armv7.zip)

**Comment by Randomxdp** [comment]
when trying to build with pacman it cloudnt verify the signature of binutils (the package i tried to build) but this is a screenshot of my attempt to run gcc and also some debugging info
![Screenshot_20221008_085747](https://user-images.githubusercontent.com/95031664/194706314-c2e6f68b-97c5-4b03-b901-688d29b2b95e.jpg)

**Comment by Maxython** [comment]
The result of `strace` is not fully shown here. Can you show the full or end result of `strace`?

**Comment by Randomxdp** [comment]
![Screenshot_20221008_112555_com termux](https://user-images.githubusercontent.com/95031664/194712481-3bc57649-e275-4e54-b3fd-0cc84369f69d.jpg)
![Screenshot_20221008_112601_com termux](https://user-images.githubusercontent.com/95031664/194712484-9d696a3e-b2a6-4005-a9db-abf6af4e83bb.jpg)

**Comment by Maxython** [comment]
@Randomxdp, now try using this glibc.

[glibc-2.36-1-armv7.zip](https://github.com/Maxython/glibc-for-termux/files/9740242/glibc-2.36-1-armv7.zip)

After you install it, you must compile one program written below based on gcc-glibc and send me the result.
```c
#include <stdio.h>
#include <time.h>
#include <fcntl.h>

int main () {
        struct timespec tp;

        if (clock_gettime(CLOCK_REALTIME, &tp) == -1) {
                perror("clock_gettime");
        }
        else {
                printf("clock_gettime success: %ld\n", tp.tv_nsec);
        }
        return 0;
}
```

**Comment by Randomxdp** [comment]
this strace was big so i made it as a video
https://user-images.githubusercontent.com/95031664/194728696-57a35e86-3e4b-492f-a4fd-29416ca56779.mp4

**Comment by Maxython** [comment]
Run this
```
gcc test.c -c test.o
strace ld -o test -dynamic-linker $PREFIX/glibc/lib/ld-linux-armhf.so.3 $PREFIX/glibc/lib/crt1.o $PREFIX/glibc/lib/crti.o -lc test.o $PREFIX/glibc/lib/crtn.o
```

**Comment by Randomxdp** [comment]
here
![Screenshot_20221009_084338](https://user-images.githubusercontent.com/95031664/194759889-3c2378c7-61ca-44e0-a6a7-fe4685550e39.jpg)
![Screenshot_20221009_084400](https://user-images.githubusercontent.com/95031664/194759891-037c3948-11aa-4785-bc51-340fa868c80c.jpg)
![Screenshot_20221009_084426](https://user-images.githubusercontent.com/95031664/194759897-dcf206d4-cf03-469c-b5ea-2fbaf64e7bba.jpg)

**Comment by Maxython** [comment]
Bruh, you didn't copy the `ld` command all the way.

**Comment by Randomxdp** [comment]
i forgor, anyways
https://user-images.githubusercontent.com/95031664/194761305-50f54807-1d26-4ff5-a1c2-75e37c7c5a89.mp4

**Comment by Maxython** [comment]
@Randomxdp, install this glibc.  

[glibc-2.36-1-armv7.zip](https://github.com/Maxython/glibc-for-termux/files/9787718/glibc-2.36-1-armv7.zip)

After that, try to compile the last file and run it (send the result).

**Comment by Randomxdp** [comment]
https://user-images.githubusercontent.com/95031664/196295868-a213fb5e-6664-4c12-9915-67e1337d5690.mp4

**Comment by Maxython** [comment]
@Randomxdp, try to do the same but only with this glibc.

[glibc-2.36-1-armv7.zip](https://github.com/Maxython/glibc-for-termux/files/9820030/glibc-2.36-1-armv7.zip)

**Comment by Randomxdp** [comment]
![Screenshot_20221022_083746](https://user-images.githubusercontent.com/95031664/197336957-2e5e6d20-6292-4b9a-bbe3-ffecbeab484f.jpg)
![Screenshot_20221022_083736](https://user-images.githubusercontent.com/95031664/197336958-52d4e2b9-7842-4d6f-93fa-94df8b7783a3.jpg)

**Comment by Maxython** [comment]
Great, you now have a working glibc (in theory). As a test, try compiling a program that doesn't require additional glibc libraries (for example, [vitetris](https://github.com/vicgeralds/vitetris)).

**Comment by Randomxdp** [comment]
yep, its working, thank you!
